# Generated by Django 6.0.3 on 2026-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'DRAFT'), ('Published', 'PUBLISHED')], default='Draft', max_length=20),
        ),
    ]
